//qtRemoteSignals auto generated file
//do not edit this file; if needed subclass it or create a decorator
//md5 hash: e7a9f0687899fa644a1ab36a7026130
#ifndef TESTDATASERVER_H
#define TESTDATASERVER_H

#include "RemoteSignals.h"

class TestDataServer : public RemoteSignals
{
	Q_OBJECT
public:
	TestDataServer(QIODevice* readDevice, QIODevice* writeDevice = 0, bool initialize = false);
signals:
	void logMessage(const QString& data);
	void logError(const QString& data);
	void echo(const QString& text);

public slots:
	void echoAnswer(const QString& text);

private:
	void processRemoteInputs(const QByteArray& data);
};

#endif //TESTDATASERVER_H
