//autogenerated file SignalProxy
#ifndef PYTHONPROCESSCLIENT_H
#define PYTHONPROCESSCLIENT_H

#include "SignalProxy.h"
#include <core/UserRequest.h>
#include <core/ScriptException.h>

class PythonProcessClient : public SignalProxy
{
	Q_OBJECT
public:
	PythonProcessClient(QIODevice& readDevice, QIODevice& writeDevice, bool initialize = false);
signals:
	void scriptPaused(const QString& file, int line);
	void printText(const QString& message);
	void printError(const QString& error);
	void createProgress(int id, const QString& name, int maximum);
	void updateProgress(int id, int progress);
	void removeProgress(int id);
	void createInfoPanel(int id, const QString& title, const QStringList& names);
	void updateInfoPanel(int id, const QStringList& values);
	void removeInfoPanel(int id);
	void clearInfo();
	void appendInfo(const QString& infoStr);
	void userRequest(const UserRequest& request);
	void userRequestAbort(int id);
	void raiseException(const ScriptException& error);
	void callRcUnit(int id, const QByteArray& unit, const QByteArray& method, const QVariantList& params);
	void updateCallStack(const QList<TraceLine>& trace);

public slots:
	void addBreakpoint(const QString& file, int line);
	void removeBreakpoint(const QString& file, int line);
	void resume();
	void stepOver();
	void stepInto();
	void stepReturn();
	void quit();
	void rcUnitResult(int id, const QVariant& result);
	void rcUnitException(int id, const QString& error);
	void requestCallStack();

private:
	void processRemoteInputs(const QByteArray& data);
};

#endif //PYTHONPROCESSCLIENT_H
