//autogenerated file SignalProxy
#include "PythonProcessClient.h"

PythonProcessClient::PythonProcessClient(QIODevice& readDevice, QIODevice& writeDevice, bool initialize)
	: SignalProxy(Q_UINT64_C(0xf2f75e3ccf9da83),Q_UINT64_C(0x4ff4a04019050c92), readDevice, writeDevice, initialize)
{}

void PythonProcessClient::addBreakpoint(const QString& file, int line)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::gid1() << SignalProxy::gid2() << (int)1;
	stream << file;
	stream << line;
	transmitSignal(msgData);
}

void PythonProcessClient::removeBreakpoint(const QString& file, int line)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::gid1() << SignalProxy::gid2() << (int)2;
	stream << file;
	stream << line;
	transmitSignal(msgData);
}

void PythonProcessClient::resume()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::gid1() << SignalProxy::gid2() << (int)3;
	transmitSignal(msgData);
}

void PythonProcessClient::stepOver()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::gid1() << SignalProxy::gid2() << (int)4;
	transmitSignal(msgData);
}

void PythonProcessClient::stepInto()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::gid1() << SignalProxy::gid2() << (int)5;
	transmitSignal(msgData);
}

void PythonProcessClient::stepReturn()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::gid1() << SignalProxy::gid2() << (int)6;
	transmitSignal(msgData);
}

void PythonProcessClient::quit()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::gid1() << SignalProxy::gid2() << (int)7;
	transmitSignal(msgData);
}

void PythonProcessClient::rcUnitResult(int id, const QVariant& result)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::gid1() << SignalProxy::gid2() << (int)23;
	stream << id;
	stream << result;
	transmitSignal(msgData);
}

void PythonProcessClient::rcUnitException(int id, const QString& error)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::gid1() << SignalProxy::gid2() << (int)24;
	stream << id;
	stream << error;
	transmitSignal(msgData);
}

void PythonProcessClient::requestCallStack()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::gid1() << SignalProxy::gid2() << (int)25;
	transmitSignal(msgData);
}

void PythonProcessClient::processRemoteInputs(const QByteArray& data)
{
	QDataStream stream(data);
	quint64 signalProxyGid1 = 0;
	quint64 signalProxyGid2 = 0;
	int signalProxyMethodId = 0;
	stream >> signalProxyGid1 >> signalProxyGid2 >> signalProxyMethodId;
	SignalProxy::checkId(signalProxyGid1, signalProxyGid2);

	if(signalProxyMethodId == 8) {
		QString file;
		int line;
		stream >> file;
		stream >> line;
		emit scriptPaused(file, line);
		return;
	}
	if(signalProxyMethodId == 9) {
		QString message;
		stream >> message;
		emit printText(message);
		return;
	}
	if(signalProxyMethodId == 10) {
		QString error;
		stream >> error;
		emit printError(error);
		return;
	}
	if(signalProxyMethodId == 11) {
		int id;
		QString name;
		int maximum;
		stream >> id;
		stream >> name;
		stream >> maximum;
		emit createProgress(id, name, maximum);
		return;
	}
	if(signalProxyMethodId == 12) {
		int id;
		int progress;
		stream >> id;
		stream >> progress;
		emit updateProgress(id, progress);
		return;
	}
	if(signalProxyMethodId == 13) {
		int id;
		stream >> id;
		emit removeProgress(id);
		return;
	}
	if(signalProxyMethodId == 14) {
		int id;
		QString title;
		QStringList names;
		stream >> id;
		stream >> title;
		stream >> names;
		emit createInfoPanel(id, title, names);
		return;
	}
	if(signalProxyMethodId == 15) {
		int id;
		QStringList values;
		stream >> id;
		stream >> values;
		emit updateInfoPanel(id, values);
		return;
	}
	if(signalProxyMethodId == 16) {
		int id;
		stream >> id;
		emit removeInfoPanel(id);
		return;
	}
	if(signalProxyMethodId == 17) {
		emit clearInfo();
		return;
	}
	if(signalProxyMethodId == 18) {
		QString infoStr;
		stream >> infoStr;
		emit appendInfo(infoStr);
		return;
	}
	if(signalProxyMethodId == 19) {
		UserRequest request;
		stream >> request;
		emit userRequest(request);
		return;
	}
	if(signalProxyMethodId == 20) {
		int id;
		stream >> id;
		emit userRequestAbort(id);
		return;
	}
	if(signalProxyMethodId == 21) {
		ScriptException error;
		stream >> error;
		emit raiseException(error);
		return;
	}
	if(signalProxyMethodId == 22) {
		int id;
		QByteArray unit;
		QByteArray method;
		QVariantList params;
		stream >> id;
		stream >> unit;
		stream >> method;
		stream >> params;
		emit callRcUnit(id, unit, method, params);
		return;
	}
	if(signalProxyMethodId == 26) {
		QList<TraceLine> trace;
		stream >> trace;
		emit updateCallStack(trace);
		return;
	}

	SignalProxy::handleError(signalProxyMethodId);
}
