//qtRemoteSignals auto generated file
//do not edit this file; if needed subclass it or create a decorator
#include "PythonProcessClient.h"

PythonProcessClient::PythonProcessClient(QIODevice* writeDevice, QIODevice* readDevice, bool initialize)
	: RemoteSignals(Q_UINT64_C(0xf2f75e3ccf9da83),Q_UINT64_C(0x4ff4a04019050c92), readDevice, writeDevice, initialize)
{}

void PythonProcessClient::addBreakpoint(const QString& file, int line)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)1;
	stream << file;
	stream << line;
	transmitSignal(msgData);
}

void PythonProcessClient::removeBreakpoint(const QString& file, int line)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)2;
	stream << file;
	stream << line;
	transmitSignal(msgData);
}

void PythonProcessClient::resume()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)3;
	transmitSignal(msgData);
}

void PythonProcessClient::stepOver()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)4;
	transmitSignal(msgData);
}

void PythonProcessClient::stepInto()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)5;
	transmitSignal(msgData);
}

void PythonProcessClient::stepReturn()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)6;
	transmitSignal(msgData);
}

void PythonProcessClient::quit()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)7;
	transmitSignal(msgData);
}

void PythonProcessClient::rcUnitResult(int id, const QVariant& result)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)23;
	stream << id;
	stream << result;
	transmitSignal(msgData);
}

void PythonProcessClient::rcUnitException(int id, const QString& error)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)24;
	stream << id;
	stream << error;
	transmitSignal(msgData);
}

void PythonProcessClient::requestCallStack()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)25;
	transmitSignal(msgData);
}

void PythonProcessClient::processRemoteInputs(const QByteArray& data)
{
	QDataStream stream(data);
	int remoteSignalVersion = 0;
	quint64 remoteSignalGid1 = 0;
	quint64 remoteSignalGid2 = 0;
	int remoteSignalMethodId = 0;
	stream >> remoteSignalVersion >> remoteSignalGid1 >> remoteSignalGid2 >> remoteSignalMethodId;
	RemoteSignals::checkId(remoteSignalVersion, remoteSignalGid1, remoteSignalGid2);

	if(remoteSignalMethodId == 8) {
		QString file;
		int line;
		stream >> file;
		stream >> line;
		emit scriptPaused(file, line);
		return;
	}
	if(remoteSignalMethodId == 9) {
		QString message;
		stream >> message;
		emit printText(message);
		return;
	}
	if(remoteSignalMethodId == 10) {
		QString error;
		stream >> error;
		emit printError(error);
		return;
	}
	if(remoteSignalMethodId == 11) {
		int id;
		QString name;
		int maximum;
		stream >> id;
		stream >> name;
		stream >> maximum;
		emit createProgress(id, name, maximum);
		return;
	}
	if(remoteSignalMethodId == 12) {
		int id;
		int progress;
		stream >> id;
		stream >> progress;
		emit updateProgress(id, progress);
		return;
	}
	if(remoteSignalMethodId == 13) {
		int id;
		stream >> id;
		emit removeProgress(id);
		return;
	}
	if(remoteSignalMethodId == 14) {
		int id;
		QString title;
		QStringList names;
		stream >> id;
		stream >> title;
		stream >> names;
		emit createInfoPanel(id, title, names);
		return;
	}
	if(remoteSignalMethodId == 15) {
		int id;
		QStringList values;
		stream >> id;
		stream >> values;
		emit updateInfoPanel(id, values);
		return;
	}
	if(remoteSignalMethodId == 16) {
		int id;
		stream >> id;
		emit removeInfoPanel(id);
		return;
	}
	if(remoteSignalMethodId == 17) {
		emit clearInfo();
		return;
	}
	if(remoteSignalMethodId == 18) {
		QString infoStr;
		stream >> infoStr;
		emit appendInfo(infoStr);
		return;
	}
	if(remoteSignalMethodId == 19) {
		UserRequest request;
		stream >> request;
		emit userRequest(request);
		return;
	}
	if(remoteSignalMethodId == 20) {
		int id;
		stream >> id;
		emit userRequestAbort(id);
		return;
	}
	if(remoteSignalMethodId == 21) {
		ScriptException error;
		stream >> error;
		emit raiseException(error);
		return;
	}
	if(remoteSignalMethodId == 22) {
		int id;
		QByteArray unit;
		QByteArray method;
		QVariantList params;
		stream >> id;
		stream >> unit;
		stream >> method;
		stream >> params;
		emit callRcUnit(id, unit, method, params);
		return;
	}
	if(remoteSignalMethodId == 26) {
		QList<TraceLine> trace;
		stream >> trace;
		emit updateCallStack(trace);
		return;
	}

	RemoteSignals::handleError(remoteSignalMethodId);
}
