//qtRemoteSignals auto generated file
//do not edit this file; if needed subclass it or create a decorator
#include "RemoteRcUnitClient.h"

RemoteRcUnitClient::RemoteRcUnitClient(QIODevice* writeDevice, QIODevice* readDevice, bool initialize)
	: RemoteSignals(Q_UINT64_C(0xc3868574fbfdf42),Q_UINT64_C(0x72910516132a7bfa), readDevice, writeDevice, initialize)
{}

void RemoteRcUnitClient::listUnits()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)1;
	transmitSignal(msgData);
}

void RemoteRcUnitClient::callMethod(const QByteArray& unit, const QByteArray& method, const QVariantList& params)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)3;
	stream << unit;
	stream << method;
	stream << params;
	transmitSignal(msgData);
}

void RemoteRcUnitClient::enableTelecontrol(const QString& unitName)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)6;
	stream << unitName;
	transmitSignal(msgData);
}

void RemoteRcUnitClient::disableTelecontrol(const QString& unitName)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)7;
	stream << unitName;
	transmitSignal(msgData);
}

void RemoteRcUnitClient::handleTcData(const QMap<int, double>& data)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)8;
	stream << data;
	transmitSignal(msgData);
}

void RemoteRcUnitClient::setTcButton(int buttonId, const bool& pressed)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)9;
	stream << buttonId;
	stream << pressed;
	transmitSignal(msgData);
}

void RemoteRcUnitClient::processRemoteInputs(const QByteArray& data)
{
	QDataStream stream(data);
	int remoteSignalVersion = 0;
	quint64 remoteSignalGid1 = 0;
	quint64 remoteSignalGid2 = 0;
	int remoteSignalMethodId = 0;
	stream >> remoteSignalVersion >> remoteSignalGid1 >> remoteSignalGid2 >> remoteSignalMethodId;
	RemoteSignals::checkId(remoteSignalVersion, remoteSignalGid1, remoteSignalGid2);

	if(remoteSignalMethodId == 2) {
		QList<RcUnitHelp> units;
		stream >> units;
		emit unitList(units);
		return;
	}
	if(remoteSignalMethodId == 4) {
		QString error;
		stream >> error;
		emit methodError(error);
		return;
	}
	if(remoteSignalMethodId == 5) {
		QVariant result;
		stream >> result;
		emit methodResponse(result);
		return;
	}

	RemoteSignals::handleError(remoteSignalMethodId);
}
