//qtRemoteSignals auto generated file
//do not edit this file; if needed subclass it or create a decorator
#include "RemoteRcUnitClientBase.h"

RemoteRcUnitClientBase::RemoteRcUnitClientBase(QIODevice* writeDevice, QIODevice* readDevice, bool initialize)
	: RemoteSignals(Q_UINT64_C(0x7192336e62a4174),Q_UINT64_C(0x77ab91543458f0), readDevice, writeDevice, initialize)
{}

void RemoteRcUnitClientBase::listUnits()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)1;
	transmitSignal(msgData);
}

void RemoteRcUnitClientBase::callMethod(uint id, const QByteArray& unit, const QByteArray& method, const QVariantList& params)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)3;
    stream << id;
	stream << unit;
	stream << method;
	stream << params;
	transmitSignal(msgData);
}

void RemoteRcUnitClientBase::enableTelecontrol(uint id, const QString& unitName)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)6;
	stream << id;
	stream << unitName;
	transmitSignal(msgData);
}

void RemoteRcUnitClientBase::disableTelecontrol(uint id, const QString& unitName)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)7;
	stream << id;
	stream << unitName;
	transmitSignal(msgData);
}

void RemoteRcUnitClientBase::handleTcData(uint id, const QMap<int, double>& data)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)8;
	stream << id;
	stream << data;
	transmitSignal(msgData);
}

void RemoteRcUnitClientBase::setTcButton(uint id, int buttonId, const bool& pressed)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)9;
	stream << id;
	stream << buttonId;
	stream << pressed;
	transmitSignal(msgData);
}

void RemoteRcUnitClientBase::updateGamepadParameters(uint id, const QString& methodName, const QString& sensName, const double& sensitivity, const QList<bool>& inverts)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)10;
	stream << id;
    stream << methodName;
	stream << sensName;
	stream << sensitivity;
	stream << inverts;
    transmitSignal(msgData);
}

void RemoteRcUnitClientBase::updateGamepadAssignment(uint id, const QString &gamepadDeviceName)
{
    QByteArray msgData;
    QDataStream stream(&msgData, QIODevice::WriteOnly);
    stream << RemoteSignals::version() << RemoteSignals::gid1() << RemoteSignals::gid2() << (int)10;
    stream << id;
    stream << gamepadDeviceName;
    transmitSignal(msgData);
}

void RemoteRcUnitClientBase::processRemoteInputs(const QByteArray& data)
{
	QDataStream stream(data);
	int remoteSignalVersion = 0;
	quint64 remoteSignalGid1 = 0;
	quint64 remoteSignalGid2 = 0;
	int remoteSignalMethodId = 0;
	stream >> remoteSignalVersion >> remoteSignalGid1 >> remoteSignalGid2 >> remoteSignalMethodId;
	RemoteSignals::checkId(remoteSignalVersion, remoteSignalGid1, remoteSignalGid2);

	if(remoteSignalMethodId == 2) {
		QList<RcUnitHelp> units;
		stream >> units;
		emit unitList(units);
		return;
	}
	if(remoteSignalMethodId == 4) {
		uint callId;
		QString error;
		stream >> callId;
		stream >> error;
		emit methodError(callId, error);
		return;
	}
	if(remoteSignalMethodId == 5) {
		uint callId;
		QVariant result;
		stream >> callId;
		stream >> result;
		emit methodResponse(callId, result);
		return;
	}
	if(remoteSignalMethodId == 11) {
		uint id;
		stream >> id;
		emit tcFinished(id);
		return;
	}

	RemoteSignals::handleError(remoteSignalMethodId);
}
