//qtRemoteSignals auto generated file
//do not edit this file; if needed subclass it or create a decorator
//md5 hash: b8b4f561830eacedaaf949ad3148f67
#ifndef REMOTERCUNITCLIENTBASE_H
#define REMOTERCUNITCLIENTBASE_H

#include "RemoteSignals.h"
#include <core/RcUnitHelp.h>

class RemoteRcUnitClientBase : public RemoteSignals
{
	Q_OBJECT
public:
	RemoteRcUnitClientBase(QIODevice* writeDevice, QIODevice* readDevice = 0, bool initialize = false);
signals:
	void unitList(const QList<RcUnitHelp>& units);
	void methodError(uint callId, const QString& error);
	void methodResponse(uint callId, const QVariant& result);

public slots:
	void listUnits();
	void callMethod(uint callId, const QByteArray& unit, const QByteArray& method, const QVariantList& params);
	void enableTelecontrol(const QString& unitName);
	void disableTelecontrol(const QString& unitName);
	void handleTcData(const QMap<int, double>& data);
	void setTcButton(int buttonId, const bool& pressed);

private:
	void processRemoteInputs(const QByteArray& data);
};

#endif //REMOTERCUNITCLIENTBASE_H
