//qtRemoteSignals auto generated file
//do not edit this file; if needed subclass it or create a decorator
//md5 hash: c3868574fbfdf4272910516132a7bfa
#ifndef REMOTERCUNITCLIENT_H
#define REMOTERCUNITCLIENT_H

#include "RemoteSignals.h"
#include <core/RcUnitHelp.h>

class RemoteRcUnitClient : public RemoteSignals
{
	Q_OBJECT
public:
	RemoteRcUnitClient(QIODevice* writeDevice, QIODevice* readDevice = 0, bool initialize = false);
signals:
	void unitList(const QList<RcUnitHelp>& units);
	void methodError(const QString& error);
	void methodResponse(const QVariant& result);

public slots:
	void listUnits();
	void callMethod(const QByteArray& unit, const QByteArray& method, const QVariantList& params);
	void enableTelecontrol(const QString& unitName);
	void disableTelecontrol(const QString& unitName);
	void handleTcData(const QMap<int, double>& data);
	void setTcButton(int buttonId, const bool& pressed);

private:
	void processRemoteInputs(const QByteArray& data);
};

#endif //REMOTERCUNITCLIENT_H
