//autogenerated file SignalProxy
#include "PythonProcessServer.h"

PythonProcessServer::PythonProcessServer(QIODevice& readDevice, QIODevice& writeDevice)
	: SignalProxy(Q_UINT64_C(0x1e849800000282), readDevice, writeDevice)
{}

void PythonProcessServer::scriptPaused(const QString& file, int line)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)9;
	stream << file;
	stream << line;
	transmitSignal(msgData);
}

void PythonProcessServer::printText(const QString& message)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)10;
	stream << message;
	transmitSignal(msgData);
}

void PythonProcessServer::printError(const QString& error)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)11;
	stream << error;
	transmitSignal(msgData);
}

void PythonProcessServer::createProgress(int id, const QString& name, int maximum)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)12;
	stream << id;
	stream << name;
	stream << maximum;
	transmitSignal(msgData);
}

void PythonProcessServer::updateProgress(int id, int progress)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)13;
	stream << id;
	stream << progress;
	transmitSignal(msgData);
}

void PythonProcessServer::removeProgress(int id)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)14;
	stream << id;
	transmitSignal(msgData);
}

void PythonProcessServer::createInfoPanel(int id, const QString& title, const QStringList& names)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)15;
	stream << id;
	stream << title;
	stream << names;
	transmitSignal(msgData);
}

void PythonProcessServer::updateInfoPanel(int id, const QStringList& values)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)16;
	stream << id;
	stream << values;
	transmitSignal(msgData);
}

void PythonProcessServer::removeInfoPanel(int id)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)17;
	stream << id;
	transmitSignal(msgData);
}

void PythonProcessServer::clearInfo()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)18;
	transmitSignal(msgData);
}

void PythonProcessServer::appendInfo(const QString& infoStr)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)19;
	stream << infoStr;
	transmitSignal(msgData);
}

void PythonProcessServer::userRequest(const UserRequest& request)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)20;
	stream << request;
	transmitSignal(msgData);
}

void PythonProcessServer::processRemoteInputs(const QByteArray& data)
{
	QDataStream stream(data);
	quint64 signalProxyGlobalId = 0;
	int signalProxyMethodId = 0;
	stream >> signalProxyGlobalId >> signalProxyMethodId;
	SignalProxy::checkId(signalProxyGlobalId);

	if(signalProxyMethodId == 1) {
		QString fileName;
		QString baseDir;
		stream >> fileName;
		stream >> baseDir;
		emit start(fileName, baseDir);
		return;
	}
	if(signalProxyMethodId == 2) {
		QString file;
		uint line;
		stream >> file;
		stream >> line;
		emit addBreakpoint(file, line);
		return;
	}
	if(signalProxyMethodId == 3) {
		QString file;
		int line;
		stream >> file;
		stream >> line;
		emit removeBreakpoint(file, line);
		return;
	}
	if(signalProxyMethodId == 4) {
		emit resume();
		return;
	}
	if(signalProxyMethodId == 5) {
		emit stepOver();
		return;
	}
	if(signalProxyMethodId == 6) {
		emit stepInto();
		return;
	}
	if(signalProxyMethodId == 7) {
		emit stepReturn();
		return;
	}
	if(signalProxyMethodId == 8) {
		emit quit();
		return;
	}

	SignalProxy::handleError(signalProxyMethodId);
}
