//autogenerated file SignalProxy
#include "PythonProcessClient.h"

PythonProcessClient::PythonProcessClient(QIODevice& readDevice, QIODevice& writeDevice)
	: SignalProxy(Q_UINT64_C(0x1e849800000282), readDevice, writeDevice)
{}

void PythonProcessClient::start(const QString& fileName, const QString& baseDir)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)1;
	stream << fileName;
	stream << baseDir;
	transmitSignal(msgData);
}

void PythonProcessClient::addBreakpoint(const QString& file, uint line)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)2;
	stream << file;
	stream << line;
	transmitSignal(msgData);
}

void PythonProcessClient::removeBreakpoint(const QString& file, int line)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)3;
	stream << file;
	stream << line;
	transmitSignal(msgData);
}

void PythonProcessClient::resume()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)4;
	transmitSignal(msgData);
}

void PythonProcessClient::stepOver()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)5;
	transmitSignal(msgData);
}

void PythonProcessClient::stepInto()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)6;
	transmitSignal(msgData);
}

void PythonProcessClient::stepReturn()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)7;
	transmitSignal(msgData);
}

void PythonProcessClient::quit()
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << SignalProxy::globalId() << (int)8;
	transmitSignal(msgData);
}

void PythonProcessClient::processRemoteInputs(const QByteArray& data)
{
	QDataStream stream(data);
	quint64 signalProxyGlobalId = 0;
	int signalProxyMethodId = 0;
	stream >> signalProxyGlobalId >> signalProxyMethodId;
	SignalProxy::checkId(signalProxyGlobalId);

	if(signalProxyMethodId == 9) {
		QString file;
		int line;
		stream >> file;
		stream >> line;
		emit scriptPaused(file, line);
		return;
	}
	if(signalProxyMethodId == 10) {
		QString message;
		stream >> message;
		emit printText(message);
		return;
	}
	if(signalProxyMethodId == 11) {
		QString error;
		stream >> error;
		emit printError(error);
		return;
	}
	if(signalProxyMethodId == 12) {
		int id;
		QString name;
		int maximum;
		stream >> id;
		stream >> name;
		stream >> maximum;
		emit createProgress(id, name, maximum);
		return;
	}
	if(signalProxyMethodId == 13) {
		int id;
		int progress;
		stream >> id;
		stream >> progress;
		emit updateProgress(id, progress);
		return;
	}
	if(signalProxyMethodId == 14) {
		int id;
		stream >> id;
		emit removeProgress(id);
		return;
	}
	if(signalProxyMethodId == 15) {
		int id;
		QString title;
		QStringList names;
		stream >> id;
		stream >> title;
		stream >> names;
		emit createInfoPanel(id, title, names);
		return;
	}
	if(signalProxyMethodId == 16) {
		int id;
		QStringList values;
		stream >> id;
		stream >> values;
		emit updateInfoPanel(id, values);
		return;
	}
	if(signalProxyMethodId == 17) {
		int id;
		stream >> id;
		emit removeInfoPanel(id);
		return;
	}
	if(signalProxyMethodId == 18) {
		emit clearInfo();
		return;
	}
	if(signalProxyMethodId == 19) {
		QString infoStr;
		stream >> infoStr;
		emit appendInfo(infoStr);
		return;
	}
	if(signalProxyMethodId == 20) {
		UserRequest request;
		stream >> request;
		emit userRequest(request);
		return;
	}

	SignalProxy::handleError(signalProxyMethodId);
}
