//autogenerated file SignalProxy
//created at:Do 25. Jul 21:56:10 2013

#include "PythonProcessClient.h"

PythonProcessClient::PythonProcessClient(QIODevice& readDevice, QIODevice& writeDevice)
	: SignalProxy(readDevice, writeDevice)
{}

void PythonProcessClient::userRequestAnswer(uint id, QVariant button, QVariant result)
{
	QByteArray msgData;
	QDataStream stream(&msgData, QIODevice::WriteOnly);
	stream << QUuid("{3cb98a50-877f-4077-923d-84874faf6be4}");
	stream << id;
	stream << button;
	stream << result;
	transmitSignal(msgData);
}

void PythonProcessClient::processRemoteInputs(const QByteArray& data)
{
	QDataStream stream(data);
	QUuid id;
	stream >> id;

	if(id == QUuid("{1b576c01-9407-43f0-90a2-f2bfc698fe9c}")) {
		QString data;
		stream >> data;
		emit logMessage(data);
		return;
	}
	if(id == QUuid("{310b87ef-ffa5-484f-aed7-de941d0752ab}")) {
		QString data;
		stream >> data;
		emit logError(data);
		return;
	}
	if(id == QUuid("{d1b9483a-0c68-4c7c-9758-0015de4b8128}")) {
		uint id;
		QString name;
		stream >> id;
		stream >> name;
		emit userRequest(id, name);
		return;
	}

	SignalProxy::handleError(id);
}
