//autogenerated file SignalProxy
//created at:Do 25. Jul 21:56:10 2013

#ifndef PYTHONPROCESSSERVER_H
#define PYTHONPROCESSSERVER_H

#include "SignalProxy.h"

class PythonProcessServer : public SignalProxy
{
	Q_OBJECT
public:
	PythonProcessServer(QIODevice& readDevice, QIODevice& writeDevice);

signals:
	void userRequestAnswer(uint id, QVariant button, QVariant result);

public slots:
	void logMessage(QString data);
	void logError(QString data);
	void userRequest(uint id, QString name);

private:
	void processRemoteInputs(const QByteArray& data);
};

#endif //PYTHONPROCESSSERVER_H
