//autogenerated file SignalProxy
//created at:Do 25. Jul 21:56:10 2013

#ifndef PYTHONPROCESSCLIENT_H
#define PYTHONPROCESSCLIENT_H

#include "SignalProxy.h"

class PythonProcessClient : public SignalProxy
{
	Q_OBJECT
public:
	PythonProcessClient(QIODevice& readDevice, QIODevice& writeDevice);

signals:
	void logMessage(QString data);
	void logError(QString data);
	void userRequest(uint id, QString name);

public slots:
	void userRequestAnswer(uint id, QVariant button, QVariant result);

private:
	void processRemoteInputs(const QByteArray& data);
};

#endif //PYTHONPROCESSCLIENT_H
