//qtRemoteSignals auto generated file
//do not edit this file; if needed subclass it or create a decorator
//md5 hash: b8b4f561830eacedaaf949ad3148f67
#ifndef REMOTERCUNITSERVERBASE_H
#define REMOTERCUNITSERVERBASE_H

#include "RemoteSignals.h"
#include <core/RcUnitHelp.h>

class RemoteRcUnitServerBase : public RemoteSignals
{
	Q_OBJECT
public:
	RemoteRcUnitServerBase(QIODevice* readDevice, QIODevice* writeDevice = 0, bool initialize = false);
signals:
	void listUnits();
	void callMethod(uint callId, const QByteArray& unit, const QByteArray& method, const QVariantList& params);
	void enableTelecontrol(const QString& unitName);
	void disableTelecontrol(const QString& unitName);
	void handleTcData(const QMap<int, double>& data);
	void setTcButton(int buttonId, const bool& pressed);

public slots:
	void unitList(const QList<RcUnitHelp>& units);
	void methodError(uint callId, const QString& error);
	void methodResponse(uint callId, const QVariant& result);

private:
	void processRemoteInputs(const QByteArray& data);
};

#endif //REMOTERCUNITSERVERBASE_H
