//qtRemoteSignals auto generated file
//do not edit this file; if needed subclass it or create a decorator
//md5 hash: 7192336e62a417477ab91543458f0
#ifndef REMOTERCUNITSERVERBASE_H
#define REMOTERCUNITSERVERBASE_H

#include "RemoteSignals.h"
#include <core/RcUnitHelp.h>

class RemoteRcUnitServerBase : public RemoteSignals
{
	Q_OBJECT
public:
	RemoteRcUnitServerBase(QIODevice* readDevice, QIODevice* writeDevice = 0, bool initialize = false);
signals:
	void listUnits();
	void callMethod(uint callId, const QByteArray& unit, const QByteArray& method, const QVariantList& params);
	void enableTelecontrol(uint id, const QString& unitName);
	void disableTelecontrol(uint id, const QString& unitName);
	void handleTcData(uint id, const QMap<int, double>& data);
	void setTcButton(uint id, int buttonId, const bool& pressed);
	void updateTcSensitivity(uint id, const QString& unitName, const QString& sensName, const double& sensitivity, const QList<bool>& inverts);

public slots:
	void unitList(const QList<RcUnitHelp>& units);
	void methodError(uint callId, const QString& error);
	void methodResponse(uint callId, const QVariant& result);
	void tcFinished(uint id);

private:
	void processRemoteInputs(const QByteArray& data);
};

#endif //REMOTERCUNITSERVERBASE_H
