//autogenerated file SignalProxy
//created at:Do 25. Jul 21:39:04 2013

#ifndef TESTDATASERVER_H
#define TESTDATASERVER_H

#include <SignalProxy.h>

class testDataServer : public SignalProxy
{
	Q_OBJECT
public:
	testDataServer(QIODevice& readDevice, QIODevice& writeDevice);

signals:
	void userRequestAnswer(uint id, QVariant button, QVariant result);

public slots:
	void logMessage(QString data);
	void logError(QString data);
	void userRequest(uint id, QString name);

private:
	void processRemoteInputs(const QByteArray& data);
};

#endif //TESTDATASERVER_H
